pipelines:
  visual:
    group: Static-Websites
    label_template: "${COUNT}"
    materials:
      visual-git:
        git: https://github.com/ukparliament/uk.parliament-visual.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          approval:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release


environments:
  WebLIVE:
    pipelines:
      - visual
